export { getPersonalityColor, PERSONALITY_COLORS } from './colors'
export { getQuestionsByAxis, QUIZ_QUESTIONS } from './questions'
export { calculateQuizResult } from './scoring'
export { getTrainingPlan, TRAINING_PLANS } from './training'
export type { TrainingSchoolMapping } from './training-schools'
export { getTrainingSchoolMapping, TRAINING_SCHOOL_MAPPINGS } from './training-schools'
export type { AxisDirection, QuizAxisDefinition } from './types'
export { ANTI_STYLE_KEYWORDS, getPersonalityType, PERSONALITY_TYPES, QUIZ_AXES } from './types'
