#!/bin/bash
# D1 資料庫 SQL 格式完整備份（標準 SQL dump）
# Usage: ./backup-d1-sql.sh [preview|production]

set -e

ENV=${1:-preview}
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="../../backups/${ENV}_sql_${TIMESTAMP}"

if [ "$ENV" != "preview" ] && [ "$ENV" != "production" ]; then
  echo "❌ 錯誤: 環境必須是 preview 或 production"
  echo "Usage: ./backup-d1-sql.sh [preview|production]"
  exit 1
fi

# 設定資料庫名稱
if [ "$ENV" = "preview" ]; then
  DB_NAME="nobodyclimb-db-preview"
else
  DB_NAME="nobodyclimb-db"
fi

echo "╔════════════════════════════════════════╗"
echo "║    D1 SQL 格式完整備份工具            ║"
echo "╚════════════════════════════════════════╝"
echo ""
echo "🌍 環境: $ENV"
echo "🗄️  資料庫: $DB_NAME"
echo "📂 備份目錄: $BACKUP_DIR"
echo ""

# 建立備份目錄
mkdir -p "$BACKUP_DIR"

# ============================================
# 方法 1: 使用 SQLite .dump 命令（推薦）
# ============================================
echo "📦 方法 1: 使用 SQLite .dump 導出完整資料庫..."

DUMP_FILE="$BACKUP_DIR/full_dump.sql"

# 執行 .dump 命令
npx wrangler d1 execute "$DB_NAME" \
  --remote \
  --command=".dump" > "$DUMP_FILE" 2>/dev/null && {
    SIZE=$(du -h "$DUMP_FILE" | cut -f1)
    LINES=$(wc -l < "$DUMP_FILE" | tr -d ' ')
    echo "   ✓ 完整備份已生成"
    echo "   📦 檔案: full_dump.sql"
    echo "   📏 大小: $SIZE"
    echo "   📄 行數: $LINES"
  } || {
    echo "   ✗ .dump 命令不支援，使用方法 2"
    rm -f "$DUMP_FILE"
  }

# ============================================
# 方法 2: 逐表導出 SQL（如果 .dump 不支援）
# ============================================
if [ ! -f "$DUMP_FILE" ] || [ ! -s "$DUMP_FILE" ]; then
  echo ""
  echo "📦 方法 2: 逐表導出 SQL..."

  # 獲取所有資料表
  TABLES_JSON=$(npx wrangler d1 execute "$DB_NAME" \
    --remote \
    --command="SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT IN ('sqlite_sequence', '_cf_KV') ORDER BY name" \
    --json 2>/dev/null)

  TABLES=$(echo "$TABLES_JSON" | jq -r '.[0].results[].name' 2>/dev/null || true)

  if [ -z "$TABLES" ]; then
    echo "❌ 錯誤: 無法取得資料表列表"
    exit 1
  fi

  TABLE_COUNT=$(echo "$TABLES" | wc -l | tr -d ' ')
  echo "   ✓ 發現 $TABLE_COUNT 個資料表"
  echo ""

  # 建立主備份檔案
  DUMP_FILE="$BACKUP_DIR/full_backup.sql"

  # 寫入 SQL header
  cat > "$DUMP_FILE" <<'EOF'
-- NobodyClimb D1 Database Backup
-- Generated by backup-d1-sql.sh
-- Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

PRAGMA foreign_keys=OFF;

EOF

  # 逐表導出
  TOTAL_RECORDS=0

  while IFS= read -r table; do
    echo "   ⏳ 導出 $table..."

    # 取得資料表結構
    set +e
    SCHEMA_JSON=$(npx wrangler d1 execute "$DB_NAME" \
      --remote \
      --command="SELECT sql FROM sqlite_master WHERE type='table' AND name='$table'" \
      --json 2>/dev/null)
    set -e

    SCHEMA=$(echo "$SCHEMA_JSON" | jq -r '.[0].results[0].sql' 2>/dev/null || echo "")

    if [ -n "$SCHEMA" ]; then
      # 寫入 CREATE TABLE
      cat >> "$DUMP_FILE" <<EOF

-- Table: $table
DROP TABLE IF EXISTS $table;
$SCHEMA;

EOF
    fi

    # 取得記錄數
    set +e
    COUNT_JSON=$(npx wrangler d1 execute "$DB_NAME" \
      --remote \
      --command="SELECT COUNT(*) as count FROM $table" \
      --json 2>/dev/null)
    set -e

    COUNT=$(echo "$COUNT_JSON" | jq -r '.[0].results[0].count' 2>/dev/null || echo "0")

    if [ "$COUNT" -eq 0 ]; then
      echo "   ⏭️  $table: 無資料"
      continue
    fi

    # 分頁導出資料（避免大型資料表超過 D1 API 回應大小限制或逾時）
    PAGE_SIZE=50
    OFFSET=0
    EXPORT_FAILED=false

    while [ "$OFFSET" -lt "$COUNT" ]; do
      # 分頁查詢（帶重試機制，最多 3 次）
      PAGE_JSON=""
      PAGE_EXIT=1
      for RETRY in 1 2 3; do
        set +e
        PAGE_JSON=$(npx wrangler d1 execute "$DB_NAME" \
          --remote \
          --command="SELECT * FROM \"$table\" LIMIT $PAGE_SIZE OFFSET $OFFSET" \
          --json 2>/dev/null)
        PAGE_EXIT=$?
        set -e
        [ "$PAGE_EXIT" -eq 0 ] && [ -n "$PAGE_JSON" ] && break || true
        [ "$RETRY" -lt 3 ] && echo "   ⚠️  $table (offset=$OFFSET): 第${RETRY}次嘗試失敗，3秒後重試..." && sleep 3 || true
      done

      if [ -z "$PAGE_JSON" ] || [ "$PAGE_EXIT" -ne 0 ]; then
        echo "   ❌ $table (offset=$OFFSET): 3次嘗試後仍失敗，略過剩餘資料"
        EXPORT_FAILED=true
        break
      fi

      # 轉換 JSON 為 INSERT SQL
      echo "$PAGE_JSON" | node -e "
        const fs = require('fs');
        let input = '';

        process.stdin.on('data', chunk => input += chunk);
        process.stdin.on('end', () => {
          try {
            const json = JSON.parse(input);
            const data = json[0]?.results || [];

            if (data.length === 0) return;

            const tableName = '$table';
            const columns = Object.keys(data[0]);
            let sql = '';

            data.forEach((row, idx) => {
              const values = columns.map(col => {
                const val = row[col];
                if (val === null || val === undefined) return 'NULL';
                if (typeof val === 'number') return val;
                if (typeof val === 'boolean') return val ? 1 : 0;
                // 處理字串（轉義單引號和反斜線）
                return \"'\" + String(val)
                  .replace(/\\\\/g, '\\\\\\\\')
                  .replace(/'/g, \"''\")
                  .replace(/\\n/g, '\\\\n')
                  .replace(/\\r/g, '\\\\r') + \"'\";
              }).join(',');

              sql += \"INSERT INTO \" + JSON.stringify(tableName) + \" (\" + columns.map(c => JSON.stringify(c)).join(',') + \") VALUES (\" + values + \");\\n\";
            });

            process.stdout.write(sql);
          } catch (e) {
            console.error('JSON parse error:', e.message);
          }
        });
      " >> "$DUMP_FILE" 2>/dev/null

      OFFSET=$((OFFSET + PAGE_SIZE))
    done

    if [ "$EXPORT_FAILED" = true ]; then
      echo "   ⚠️  $table: 部分資料匯出失敗（已匯出至 offset=$OFFSET）"
    else
      echo "   ✓ $table: $COUNT 筆記錄"
      TOTAL_RECORDS=$((TOTAL_RECORDS + COUNT))
    fi

  done <<< "$TABLES"

  # 寫入 SQL footer
  cat >> "$DUMP_FILE" <<'EOF'

PRAGMA foreign_keys=ON;

-- End of backup
EOF

  echo ""
  echo "   ✓ 總計 $TOTAL_RECORDS 筆記錄"
fi

# ============================================
# 建立備份資訊檔案
# ============================================
echo ""
echo "📝 建立備份資訊..."

# 統計資訊
if [ -f "$DUMP_FILE" ]; then
  SIZE=$(du -h "$DUMP_FILE" | cut -f1)
  LINES=$(wc -l < "$DUMP_FILE" | tr -d ' ')
  TABLE_COUNT=$(grep -c "^CREATE TABLE" "$DUMP_FILE" || echo "0")
  INSERT_COUNT=$(grep -c "^INSERT INTO" "$DUMP_FILE" || echo "0")
fi

cat > "$BACKUP_DIR/backup_info.json" <<EOF
{
  "environment": "$ENV",
  "database": "$DB_NAME",
  "timestamp": "$TIMESTAMP",
  "date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "format": "sql",
  "file": "$(basename "$DUMP_FILE")",
  "size": "$SIZE",
  "lines": $LINES,
  "table_count": $TABLE_COUNT,
  "insert_count": $INSERT_COUNT
}
EOF

# 建立 README
cat > "$BACKUP_DIR/README.md" <<EOF
# D1 資料庫 SQL 備份

## 備份資訊
- **環境**: $ENV
- **資料庫**: $DB_NAME
- **時間**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
- **格式**: SQL
- **檔案**: $(basename "$DUMP_FILE")
- **大小**: $SIZE
- **資料表**: $TABLE_COUNT 個
- **記錄**: $INSERT_COUNT 筆

## 還原指令

\`\`\`bash
# 還原到 Preview
./restore-d1-sql.sh $(basename "$BACKUP_DIR") preview

# 還原到 Production
./restore-d1-sql.sh $(basename "$BACKUP_DIR") production
\`\`\`

## 手動還原

\`\`\`bash
# 直接執行 SQL 檔案
cd backend
npx wrangler d1 execute $DB_NAME --remote --file=../backups/$(basename "$BACKUP_DIR")/$(basename "$DUMP_FILE")
\`\`\`

## 檢查備份內容

\`\`\`bash
# 查看資料表列表
grep "^CREATE TABLE" $(basename "$DUMP_FILE")

# 查看記錄數
grep -c "^INSERT INTO" $(basename "$DUMP_FILE")

# 查看特定資料表
grep "CREATE TABLE.*users" $(basename "$DUMP_FILE") -A 10
\`\`\`
EOF

echo "   ✓ 備份資訊已建立"

# ============================================
# 壓縮備份
# ============================================
echo ""
read -p "是否壓縮備份? (y/n): " compress

if [ "$compress" = "y" ] || [ "$compress" = "Y" ]; then
  echo "🗜️  壓縮備份中..."

  ARCHIVE_NAME="${ENV}_sql_${TIMESTAMP}.tar.gz"
  tar -czf "../../backups/$ARCHIVE_NAME" -C "../../backups" "$(basename "$BACKUP_DIR")" && {
    ARCHIVE_SIZE=$(du -h "../../backups/$ARCHIVE_NAME" | cut -f1)
    echo "   ✓ 已壓縮: $ARCHIVE_NAME"
    echo "   📦 大小: $ARCHIVE_SIZE"

    read -p "是否刪除原始備份目錄? (y/n): " delete
    if [ "$delete" = "y" ] || [ "$delete" = "Y" ]; then
      rm -rf "$BACKUP_DIR"
      echo "   ✓ 已刪除原始目錄"
    fi
  } || {
    echo "   ✗ 壓縮失敗"
  }
fi

# ============================================
# 完成
# ============================================
echo ""
echo "✅ SQL 備份完成！"
echo ""
echo "📊 備份統計:"
echo "   - 檔案: $(basename "$DUMP_FILE")"
echo "   - 大小: $SIZE"
echo "   - 資料表: $TABLE_COUNT 個"
echo "   - INSERT 語句: $INSERT_COUNT 筆"
echo ""
echo "📁 備份位置: $BACKUP_DIR"
echo ""
echo "💡 還原指令:"
echo "   ./restore-d1-sql.sh $(basename "$BACKUP_DIR") production"
echo ""
echo "💡 直接執行 SQL:"
echo "   cd ../../backend"
echo "   npx wrangler d1 execute $DB_NAME --remote --file=../backups/$(basename "$BACKUP_DIR")/$(basename "$DUMP_FILE")"
