#!/bin/bash
# D1 資料庫 SQL 格式完整備份（修正版）
# Usage: ./backup-d1-sql-fixed.sh [preview|production]

set -e

ENV=${1:-preview}
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="../../backups/${ENV}_sql_${TIMESTAMP}"

if [ "$ENV" != "preview" ] && [ "$ENV" != "production" ]; then
  echo "❌ 錯誤: 環境必須是 preview 或 production"
  echo "Usage: ./backup-d1-sql-fixed.sh [preview|production]"
  exit 1
fi

# 設定資料庫名稱
if [ "$ENV" = "preview" ]; then
  DB_NAME="nobodyclimb-db-preview"
else
  DB_NAME="nobodyclimb-db"
fi

echo "╔════════════════════════════════════════╗"
echo "║    D1 SQL 完整備份工具（修正版）      ║"
echo "╚════════════════════════════════════════╝"
echo ""
echo "🌍 環境: $ENV"
echo "🗄️  資料庫: $DB_NAME"
echo "📂 備份目錄: $BACKUP_DIR"
echo ""

# 建立備份目錄
mkdir -p "$BACKUP_DIR"

# ============================================
# 獲取所有資料表列表
# ============================================
echo "🔍 發現資料表..."

TABLES_JSON=$(npx wrangler d1 execute "$DB_NAME" \
  --remote \
  --command="SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT IN ('sqlite_sequence', '_cf_KV') ORDER BY name" \
  --json 2>/dev/null)

TABLES=$(echo "$TABLES_JSON" | jq -r '.[0].results[].name' 2>/dev/null || true)

if [ -z "$TABLES" ]; then
  echo "❌ 錯誤: 無法取得資料表列表"
  exit 1
fi

TABLE_COUNT=$(echo "$TABLES" | wc -l | tr -d ' ')
echo "   ✓ 發現 $TABLE_COUNT 個資料表"
echo ""

# ============================================
# 建立主備份檔案
# ============================================
DUMP_FILE="$BACKUP_DIR/full_backup.sql"

cat > "$DUMP_FILE" <<EOF
-- NobodyClimb D1 Database Backup
-- Generated by backup-d1-sql-fixed.sh
-- Environment: $ENV
-- Database: $DB_NAME
-- Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
-- Note: PRAGMA and TRANSACTION statements removed for D1 compatibility

EOF

# ============================================
# 第一階段：收集所有表的結構和資料
# ============================================
echo "📦 階段 1: 收集資料表結構和資料..."

TOTAL_RECORDS=0
SUCCESS_COUNT=0

# 建立臨時目錄存放各表的 schema 和 data
SCHEMA_DIR="$BACKUP_DIR/schemas"
DATA_DIR="$BACKUP_DIR/data"
mkdir -p "$SCHEMA_DIR" "$DATA_DIR"

while IFS= read -r table; do
  echo "   ⏳ 收集 $table..."

  # 1. 取得資料表結構
  SCHEMA_JSON=$(npx wrangler d1 execute "$DB_NAME" \
    --remote \
    --command="SELECT sql FROM sqlite_master WHERE type='table' AND name='$table'" \
    --json 2>/dev/null)

  SCHEMA=$(echo "$SCHEMA_JSON" | jq -r '.[0].results[0].sql' 2>/dev/null || echo "")

  if [ -n "$SCHEMA" ]; then
    cat > "$SCHEMA_DIR/${table}.sql" <<EOF
-- ============================================
-- Table: $table
-- ============================================
DROP TABLE IF EXISTS "$table";
$SCHEMA;

EOF
  fi

  # 2. 取得記錄數
  COUNT_JSON=$(npx wrangler d1 execute "$DB_NAME" \
    --remote \
    --command="SELECT COUNT(*) as count FROM \"$table\"" \
    --json 2>/dev/null)

  COUNT=$(echo "$COUNT_JSON" | jq -r '.[0].results[0].count' 2>/dev/null || echo "0")

  if [ "$COUNT" -eq 0 ]; then
    echo "   ⏭️  $table: 無資料"
    continue
  fi

  # 3. 導出資料
  DATA_JSON=$(npx wrangler d1 execute "$DB_NAME" \
    --remote \
    --command="SELECT * FROM \"$table\"" \
    --json 2>/dev/null)

  # 儲存到臨時 JSON 檔案
  echo "$DATA_JSON" > "$BACKUP_DIR/temp_${table}.json"

  # 使用 Node.js 腳本轉換為 INSERT 語句
  TABLE_NAME="$table" JSON_FILE="$BACKUP_DIR/temp_${table}.json" node << 'NODEJS_SCRIPT' > "$DATA_DIR/${table}.sql"
const fs = require('fs');
const jsonFile = process.env.JSON_FILE;
const tableName = process.env.TABLE_NAME;

try {
  const content = fs.readFileSync(jsonFile, 'utf-8');
  const json = JSON.parse(content);
  const data = json[0]?.results || [];

  if (data.length === 0) {
    process.exit(0);
  }

  const columns = Object.keys(data[0]);

  data.forEach(row => {
    const values = columns.map(col => {
      const val = row[col];
      if (val === null || val === undefined) return 'NULL';
      if (typeof val === 'number') return val;
      if (typeof val === 'boolean') return val ? 1 : 0;

      // 處理字串（轉義特殊字元）
      const str = String(val)
        .replace(/\\/g, '\\\\')   // 反斜線
        .replace(/'/g, "''")      // 單引號
        .replace(/\n/g, '\\n')    // 換行
        .replace(/\r/g, '\\r')    // 回車
        .replace(/\t/g, '\\t')    // Tab
        .replace(/\0/g, '\\0');   // Null字元

      return `'${str}'`;
    }).join(',');

    const columnNames = columns.map(c => `"${c}"`).join(',');
    console.log(`INSERT INTO "${tableName}" (${columnNames}) VALUES (${values});`);
  });
} catch (e) {
  console.error(`-- Error processing ${tableName}:`, e.message);
  process.exit(1);
}
NODEJS_SCRIPT

  if [ $? -eq 0 ]; then
    echo "   ✓ $table: $COUNT 筆記錄"
    TOTAL_RECORDS=$((TOTAL_RECORDS + COUNT))
    SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
  else
    echo "   ✗ $table: 轉換失敗"
  fi

  # 清理臨時 JSON 檔案
  rm -f "$BACKUP_DIR/temp_${table}.json"

done <<< "$TABLES"

# ============================================
# 第二階段：按正確順序寫入 SQL 檔案
# ============================================
echo ""
echo "📝 階段 2: 組合 SQL 檔案..."

# 2.1 寫入所有表結構
echo "   ⏳ 寫入表結構..."
for schema_file in "$SCHEMA_DIR"/*.sql; do
  [ -f "$schema_file" ] && cat "$schema_file" >> "$DUMP_FILE"
done

# 2.2 寫入資料區段標記
cat >> "$DUMP_FILE" <<'EOF'

-- ============================================
-- DATA SECTION
-- ============================================

EOF

# 2.3 寫入所有 INSERT 語句（按依賴順序）
echo "   ⏳ 寫入資料..."

# 定義表的插入順序（父表優先）
INSERT_ORDER=(
  "d1_migrations"
  "users"
  "biographies"
  "crags"
  "gyms"
  "videos"
  "posts"
  "galleries"
  "routes"
  "biography_videos"
  "biography_instagrams"
  "biography_likes"
  "biography_views"
  "biography_core_stories"
  "biography_one_liners"
  "biography_stories"
  "bucket_list_items"
  "bucket_list_comments"
  "bucket_list_likes"
  "bucket_list_references"
  "climbing_locations"
  "story_prompts"
  "follows"
  "bookmarks"
  "likes"
  "comments"
  "notifications"
  "refresh_tokens"
  "user_badges"
  "post_tags"
  "gallery_images"
  "reviews"
)

# 按順序寫入資料
for table in "${INSERT_ORDER[@]}"; do
  data_file="$DATA_DIR/${table}.sql"
  [ -f "$data_file" ] && cat "$data_file" >> "$DUMP_FILE"
done

# 寫入剩餘的表（如果有的話）
for data_file in "$DATA_DIR"/*.sql; do
  table_name=$(basename "$data_file" .sql)
  # 檢查是否已經處理過
  if [[ ! " ${INSERT_ORDER[@]} " =~ " ${table_name} " ]]; then
    cat "$data_file" >> "$DUMP_FILE"
  fi
done

# 清理臨時目錄
rm -rf "$SCHEMA_DIR" "$DATA_DIR"

# ============================================
# SQL Footer
# ============================================
cat >> "$DUMP_FILE" <<'EOF'

-- End of backup
EOF

echo ""
echo "   ✓ 總計 $TOTAL_RECORDS 筆記錄"

# ============================================
# 統計資訊
# ============================================
echo ""
echo "📝 建立備份資訊..."

SIZE=$(du -h "$DUMP_FILE" | cut -f1)
LINES=$(wc -l < "$DUMP_FILE" | tr -d ' ')
TABLE_COUNT_ACTUAL=$(grep -c "^DROP TABLE IF EXISTS" "$DUMP_FILE" || echo "0")
INSERT_COUNT=$(grep -c "^INSERT INTO" "$DUMP_FILE" || echo "0")

cat > "$BACKUP_DIR/backup_info.json" <<EOF
{
  "environment": "$ENV",
  "database": "$DB_NAME",
  "timestamp": "$TIMESTAMP",
  "date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "format": "sql",
  "file": "$(basename "$DUMP_FILE")",
  "size": "$SIZE",
  "lines": $LINES,
  "table_count": $TABLE_COUNT_ACTUAL,
  "insert_count": $INSERT_COUNT,
  "total_records": $TOTAL_RECORDS
}
EOF

# ============================================
# 建立 README
# ============================================
cat > "$BACKUP_DIR/README.md" <<EOF
# D1 資料庫 SQL 備份

## 備份資訊
- **環境**: $ENV
- **資料庫**: $DB_NAME
- **時間**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
- **格式**: SQL
- **檔案**: $(basename "$DUMP_FILE")
- **大小**: $SIZE
- **資料表**: $TABLE_COUNT_ACTUAL 個
- **總記錄**: $TOTAL_RECORDS 筆
- **INSERT 語句**: $INSERT_COUNT 筆

## 還原指令

\`\`\`bash
# 還原到 Preview
./restore-d1-sql.sh $(basename "$BACKUP_DIR") preview

# 還原到 Production
./restore-d1-sql.sh $(basename "$BACKUP_DIR") production
\`\`\`

## 手動還原

\`\`\`bash
cd backend
npx wrangler d1 execute $DB_NAME --remote \\
  --file=../backups/$(basename "$BACKUP_DIR")/$(basename "$DUMP_FILE")
\`\`\`

## 驗證備份

\`\`\`bash
# 查看資料表
grep "^DROP TABLE" full_backup.sql

# 查看記錄數
grep -c "^INSERT INTO" full_backup.sql

# 查看特定資料表的資料
grep "INSERT INTO.*users" full_backup.sql | head -5
\`\`\`
EOF

echo "   ✓ 備份資訊已建立"

# ============================================
# 驗證備份
# ============================================
echo ""
echo "🔍 驗證備份內容..."

# 檢查是否有實際的 INSERT 語句
SAMPLE_INSERT=$(grep "^INSERT INTO" "$DUMP_FILE" | head -1)

if [ -n "$SAMPLE_INSERT" ]; then
  echo "   ✓ 備份包含實際資料"
  echo "   範例: ${SAMPLE_INSERT:0:80}..."
else
  echo "   ⚠️  警告: 備份中沒有找到 INSERT 語句"
fi

# ============================================
# 壓縮備份
# ============================================
echo ""
read -p "是否壓縮備份? (y/n): " compress

if [ "$compress" = "y" ] || [ "$compress" = "Y" ]; then
  echo "🗜️  壓縮備份中..."

  ARCHIVE_NAME="${ENV}_sql_${TIMESTAMP}.tar.gz"
  tar -czf "../../backups/$ARCHIVE_NAME" -C "../../backups" "$(basename "$BACKUP_DIR")" && {
    ARCHIVE_SIZE=$(du -h "../../backups/$ARCHIVE_NAME" | cut -f1)
    echo "   ✓ 已壓縮: $ARCHIVE_NAME"
    echo "   📦 大小: $ARCHIVE_SIZE"

    read -p "是否刪除原始備份目錄? (y/n): " delete
    if [ "$delete" = "y" ] || [ "$delete" = "Y" ]; then
      rm -rf "$BACKUP_DIR"
      echo "   ✓ 已刪除原始目錄"
    fi
  } || {
    echo "   ✗ 壓縮失敗"
  }
fi

# ============================================
# 完成
# ============================================
echo ""
echo "✅ SQL 備份完成！"
echo ""
echo "📊 備份統計:"
echo "   - 成功: $SUCCESS_COUNT 個資料表"
echo "   - 總記錄: $TOTAL_RECORDS 筆"
echo "   - 檔案大小: $SIZE"
echo "   - INSERT 語句: $INSERT_COUNT 筆"
echo ""
echo "📁 備份位置: $BACKUP_DIR"
echo ""
echo "💡 還原指令:"
echo "   ./restore-d1-sql.sh $(basename "$BACKUP_DIR") production"
